export const INITIALS = [
  '',
  'b',
  'p',
  'm',
  'd',
  't',
  'n',
  'l',
  's',
  'z',
  'c',
  'g',
  'k',
  'ng',
  'h',
  'w',
  'j',
  'nj',
] as const;
export const FINALS = [
  'a',
  'ai',
  'au',
  'ang',
  'aing',
  'ah',
  'ak',
  'aik',
  'e',
  'ei',
  'eo',
  'eoy',
  'eu',
  'eing',
  'eoyng',
  'eh',
  'ek',
  'eih',
  'eik',
  'eoh',
  'eoyh',
  'eoyk',
  'i',
  'ia',
  'iau',
  'ie',
  'ieu',
  'iu',
  'ing',
  'iang',
  'ieng',
  'ih',
  'ik',
  'iah',
  'iak',
  'iauh',
  'ieh',
  'iek',
  'ng',
  'o',
  'oo',
  'ooy',
  'ou',
  'ooung',
  'ooyng',
  'oung',
  'oh',
  'ooh',
  'oouk',
  'ouh',
  'ouk',
  'ooyk',
  'u',
  'ua',
  'uai',
  'ui',
  'uo',
  'uoi',
  'ung',
  'uang',
  'uong',
  'uh',
  'uk',
  'uah',
  'uak',
  'uoh',
  'uok',
  'y',
  'yo',
  'yng',
  'yong',
  'yh',
  'yk',
  'yoh',
  'yok',
] as const;
export const TONES = [
  '', // 无固定声调，对应花括号标记
  '0',
  '21',
  '24',
  '242',
  '33',
  '5',
  '53',
  '55',
] as const;

export type Initial = (typeof INITIALS)[number];
export type Final = (typeof FINALS)[number];
export type Tone = (typeof TONES)[number];
export enum ToneCategory {
  Yinping = '阴平',
  Yangping = '阳平',
  Shang = '上',
  YingQu = '阴去',
  YangQu = '阳去',
  YinRu = '阴入',
  YangRu = '阳入',
}

export const toneCategoryMap: Record<Tone, ToneCategory | null> = {
  '55': ToneCategory.Yinping,
  '53': ToneCategory.Yangping,
  '33': ToneCategory.Shang,
  '21': ToneCategory.YingQu,
  '242': ToneCategory.YangQu,
  '24': ToneCategory.YinRu,
  '5': ToneCategory.YangRu,
  '0': null,
  '': null,
} as const;

export const sourceMap: Record<string, string> = {
  feng: '福州方言词典',
  cikling: '戚林八音校注',
};

export const sourceQuoteMap: Record<string, string> = {
  feng: '《福州方言词典》',
  cikling: '《戚林八音校注》',
  dfd: '《Dictionary of Foochow Dialect》',
  ime: '输入法',
};

export const toneCikLingMap: Record<string, string> = {
  '': '未知',
  1: '上平',
  2: '上上',
  3: '上去',
  4: '上入',
  5: '下平',
  6: '下上',
  7: '下去',
  8: '下入',
};

export const yngpingFengIPAInitialMap: Record<Initial, string> = {
  '': '',
  b: 'p',
  p: 'p’',
  m: 'm',
  d: 't',
  t: 't’',
  n: 'n',
  l: 'l',
  s: 's',
  z: 'ts',
  c: 'ts’',
  g: 'k',
  k: 'k’',
  ng: 'ŋ',
  h: 'h',
  w: 'β',
  j: 'ʒ',
  nj: 'ʒ',
};

export const yngpingFengIPAFinalMap: Record<Final, string> = {
  a: 'a',
  //   "a": "ɑ",
  ai: 'ai',
  au: 'au',
  ang: 'aŋ',
  aing: 'aiŋ',
  ah: 'aʔ',
  ak: 'aʔ',
  aik: 'aiʔ',
  e: 'ɛ',
  ei: 'ɛi',
  eo: 'œ',
  eoy: 'øy',
  eu: 'ɛu',
  eing: 'ɛiŋ',
  eoyng: 'øyŋ',
  eh: 'ɛʔ',
  ek: 'ɛʔ',
  eih: 'ɛiʔ',
  eik: 'ɛiʔ',
  eoh: 'œʔ',
  eoyh: 'øyʔ',
  eoyk: 'øyʔ',
  i: 'i',
  ia: 'ia',
  iau: 'iau',
  iauh: 'iauʔ',
  ie: 'ie',
  ieu: 'ieu',
  iu: 'ieu',
  iang: 'iaŋ',
  ieng: 'ieŋ',
  ing: 'iŋ',
  ih: 'iʔ',
  ik: 'iʔ',
  iah: 'iaʔ',
  iak: 'iaʔ',
  ieh: 'ieʔ',
  iek: 'ieʔ',
  ng: 'ŋ̍',
  o: 'o',
  // "o": "ɔ",
  oo: 'ɔ',
  ooy: 'ɔy',
  ou: 'ou',
  ooung: 'ɔuŋ',
  ooyng: 'ɔyŋ',
  oung: 'ouŋ',
  oh: 'oʔ',
  ooh: 'ɔʔ',
  oouk: 'ɔuʔ',
  ooyk: 'ɔyʔ',
  ouh: 'ouʔ',
  ouk: 'ouʔ',
  u: 'u',
  ua: 'ua',
  uai: 'uai',
  ui: 'uoi',
  uo: 'uo',
  uoi: 'uoi',
  ung: 'uŋ',
  uang: 'uaŋ',
  uong: 'uoŋ',
  uh: 'uʔ',
  uk: 'uʔ',
  uah: 'uaʔ',
  uak: 'uaʔ',
  uoh: 'uoʔ',
  uok: 'uoʔ',
  y: 'y',
  yo: 'yo',
  yng: 'yŋ',
  yong: 'yoŋ',
  yh: 'yʔ',
  yk: 'yʔ',
  yoh: 'yoʔ',
  yok: 'yoʔ',
};

export const yngpingFengIPAToneMap: Record<string, string> = {
  0: '',
  21: '˨˩',
  213: '˨˩˨',
  24: '˧˥',
  242: '˨˦˨',
  33: '˧˧',
  5: '˥',
  53: '˥˧',
  55: '˥˥',
};

export const yngpingFengIPAEndToneMap: Record<string, string> = {
  0: '',
  21: '˨˩',
  213: '˨˩˨',
  24: '˨˦',
  242: '˨˦˨',
  33: '˧˧',
  5: '˥',
  53: '˥˧',
  55: '˥˥',
};
// 一对二的映射：原书ipa将单字调的24记为“˨˦”。而连读中的24，记为“˧˥”，此为五度中的35。
// 这种一对二的映射有两种快捷的解决办法。
// 1.暴力映射，只要不处在多音节词汇末尾的24，统统转换为“˧˥”（即35）。
// 2.无视这种差异，在线上词典说明页面说明即可。个人建议选第一种。

export const yngpingIPAInitialMap: Record<Initial, string> = {
  '': '',
  b: 'p',
  p: 'pʰ',
  m: 'm',
  d: 't',
  t: 'tʰ',
  n: 'n',
  l: 'l',
  s: 's',
  z: 't͡s',
  c: 't͡sʰ',
  g: 'k',
  k: 'kʰ',
  ng: 'ŋ',
  h: 'h',
  w: 'β̞',
  j: 'ɹ',
  nj: 'ɹ̃',
};

export const yngpingIPAFinalMap: Record<Final, string> = {
  a: 'a',
  ai: 'ai',
  au: 'au',
  ang: 'aŋ',
  aing: 'aiŋ',
  ah: 'aʔ',
  ak: 'aʔ',
  aik: 'aiʔ',
  e: 'e',
  ei: 'ei',
  eo: 'ø',
  eoy: 'øy',
  eu: 'eu',
  eing: 'eiŋ',
  eoyng: 'øyŋ',
  eh: 'eʔ',
  ek: 'eʔ',
  eih: 'eiʔ',
  eik: 'eiʔ',
  eoh: 'øʔ',
  eoyh: 'øyʔ',
  eoyk: 'øyʔ',
  i: 'i',
  ia: 'ia',
  iau: 'iau',
  ie: 'ie',
  ieu: 'ieu',
  iu: 'iu',
  ing: 'iŋ',
  iang: 'iaŋ',
  ieng: 'ieŋ',
  ih: 'iʔ',
  ik: 'iʔ',
  iah: 'iaʔ',
  iak: 'iaʔ',
  iauh: 'iauʔ',
  ieh: 'ieʔ',
  iek: 'ieʔ',
  ng: 'ŋ̍',
  o: 'o',
  oo: 'ɒ',
  ooy: 'ɒy',
  ou: 'ou',
  ooung: 'ɒuŋ',
  ooyng: 'ɒyŋ',
  oung: 'ouŋ',
  oh: 'oʔ',
  ooh: 'ɒʔ',
  oouk: 'ɒuʔ',
  ouh: 'ouʔ',
  ouk: 'ouʔ',
  ooyk: 'ɒyʔ',
  u: 'u',
  ua: 'ua',
  uai: 'uai',
  ui: 'ui',
  uo: 'uo',
  uoi: 'uoi',
  ung: 'uŋ',
  uang: 'uaŋ',
  uong: 'uoŋ',
  uh: 'uʔ',
  uk: 'uʔ',
  uah: 'uaʔ',
  uak: 'uaʔ',
  uoh: 'uoʔ',
  uok: 'uoʔ',
  y: 'y',
  yo: 'yo',
  yng: 'yŋ',
  yong: 'yoŋ',
  yh: 'yʔ',
  yk: 'yʔ',
  yoh: 'yoʔ',
  yok: 'yoʔ',
};

export const yngpingIPAToneMap: Record<Tone, string> = {
  '': '',
  0: '',
  21: '˨˩',
  24: '˧˥',
  242: '˨˦˨',
  33: '˧˧',
  5: '˥',
  53: '˥˧',
  55: '˥˥',
};

export const phonologyBanguaceInitialMap: Record<string, string> = {
  柳: 'l',
  邊: 'b',
  求: 'g',
  氣: 'k',
  低: 'd',
  波: 'p',
  他: 't',
  曾: 'c',
  日: 'n',
  時: 's',
  鶯: '',
  蒙: 'm',
  語: 'ng',
  出: 'ch',
  喜: 'h',
};

export const phonologyBanguaceRhythmMap: Record<string, string> = {
  伓下去: 'n̂g',
  春上平: 'ŭng',
  春上上: 'ūng',
  春上去: 'óng',
  春上入: 'ók',
  春下平: 'ùng',
  春下去: 'ông',
  春下入: 'ŭk',
  花上平: 'uă',
  花上上: 'uā',
  花上去: 'uá',
  花上入: 'uáh',
  花下平: 'uà',
  花下去: 'uâ',
  花下入: 'uăh',
  香上平: 'iŏng',
  香上上: 'iōng',
  香上去: 'ióng',
  香上入: 'iók',
  香下平: 'iòng',
  香下去: 'iông',
  香下入: 'iŏk',
  秋上平: 'ĭu',
  秋上上: 'īu',
  秋上去: 'éu',
  秋上入: 'éuh',
  秋下平: 'ìu',
  秋下去: 'êu',
  秋下入: 'ĭuh',
  山上平: 'ăng',
  山上上: 'āng',
  山上去: 'áng',
  山上入: 'ák',
  山下平: 'àng',
  山下去: 'âng',
  山下入: 'ăk',
  開上平: 'ăi',
  開上上: 'āi',
  開上去: 'ái',
  開上入: 'áih',
  開下平: 'ài',
  開下去: 'âi',
  開下入: 'ăih',
  嘉上平: 'ă',
  嘉上上: 'ā',
  嘉上去: 'á',
  嘉上入: 'áh',
  嘉下平: 'à',
  嘉下去: 'â',
  嘉下入: 'ăh',
  賓上平: 'ĭng',
  賓上上: 'īng',
  賓上去: 'éng',
  賓上入: 'ék',
  賓下平: 'ìng',
  賓下去: 'êng',
  賓下入: 'ĭk',
  歡上平: 'uăng',
  歡上上: 'uāng',
  歡上去: 'uáng',
  歡上入: 'uák',
  歡下平: 'uàng',
  歡下去: 'uâng',
  歡下入: 'uăk',
  歌上平: 'ŏ̤',
  歌上上: 'ō̤',
  歌上去: 'ó̤',
  歌上入: 'ó̤h',
  歌下平: 'ò̤',
  歌下去: 'ô̤',
  歌下入: 'ŏ̤h',
  須上平: 'ṳ̆',
  須上上: 'ṳ̄',
  須上去: 'é̤ṳ',
  須上入: 'é̤ṳh',
  須下平: 'ṳ̀',
  須下去: 'ê̤ṳ',
  須下入: 'ṳ̆h',
  杯上平: 'uŏi',
  杯上上: 'uōi',
  杯上去: 'uói',
  杯上入: 'uóih',
  杯下平: 'uòi',
  杯下去: 'uôi',
  杯下入: 'uŏih',
  孤上平: 'ŭ',
  孤上上: 'ū',
  孤上去: 'ó',
  孤上入: 'óh',
  孤下平: 'ù',
  孤下去: 'ô',
  孤下入: 'ŭh',
  燈上平: 'ĕng',
  燈上上: 'ēng',
  燈上去: 'áing',
  燈上入: 'áik',
  燈下平: 'èng',
  燈下去: 'âing',
  燈下入: 'ĕk',
  光上平: 'uŏng',
  光上上: 'uōng',
  光上去: 'uóng',
  光上入: 'uók',
  光下平: 'uòng',
  光下去: 'uông',
  光下入: 'uŏk',
  輝上平: 'ŭi',
  輝上上: 'ūi',
  輝上去: 'ói',
  輝上入: 'óih',
  輝下平: 'ùi',
  輝下去: 'ôi',
  輝下入: 'ŭih',
  燒上平: 'iĕu',
  燒上上: 'iēu',
  燒上去: 'iéu',
  燒上入: 'iéuh',
  燒下平: 'ièu',
  燒下去: 'iêu',
  燒下入: 'iĕuh',
  銀上平: 'ṳ̆ng',
  銀上上: 'ṳ̄ng',
  銀上去: 'é̤ṳng',
  銀上入: 'é̤ṳk',
  銀下平: 'ṳ̀ng',
  銀下去: 'ê̤ṳng',
  銀下入: 'ṳ̆k',
  釭上平: 'ŏng',
  釭上上: 'ōng',
  釭上去: 'áung',
  釭上入: 'áuk',
  釭下平: 'òng',
  釭下去: 'âung',
  釭下入: 'ŏk',
  之上平: 'ĭ',
  之上上: 'ī',
  之上去: 'é',
  之上入: 'éh',
  之下平: 'ì',
  之下去: 'ê',
  之下入: 'ĭh',
  東上平: 'ĕ̤ng',
  東上上: 'ē̤ng',
  東上去: 'áe̤ng',
  東上入: 'áe̤k',
  東下平: 'è̤ng',
  東下去: 'âe̤ng',
  東下入: 'ĕ̤k',
  郊上上: 'āu',
  郊上平: 'ău',
  郊上去: 'áu',
  郊上入: 'áuh',
  郊下平: 'àu',
  郊下去: 'âu',
  郊下入: 'ăuh',
  過上平: 'uŏ',
  過上上: 'uō',
  過上去: 'uó',
  過上入: 'uóh',
  過下平: 'uò',
  過下去: 'uô',
  過下入: 'uŏh',
  西上平: 'ă̤',
  西上上: 'ā̤',
  西上去: 'á̤',
  西上入: 'á̤h',
  西下平: 'à̤',
  西下去: 'â̤',
  西下入: 'ă̤h',
  橋上平: 'iŏ',
  橋上上: 'iō',
  橋上去: 'ió',
  橋上入: 'ióh',
  橋下平: 'iò',
  橋下去: 'iô',
  橋下入: 'iŏh',
  雞上平: 'iĕ',
  雞上上: 'iē',
  雞上去: 'ié',
  雞上入: 'iéh',
  雞下平: 'iè',
  雞下去: 'iê',
  雞下入: 'iĕh',
  聲上上: 'iāng',
  聲上去: 'iáng',
  聲上入: 'iák',
  聲下平: 'iàng',
  聲下去: 'iâng',
  聲下入: 'iăk',
  聲上平: 'iăng',
  催上平: 'ŏi',
  催上上: 'ōi',
  催上去: 'ó̤i',
  催上入: 'ó̤ih',
  催下平: 'òi',
  催下去: 'ô̤i',
  催下入: 'ŏih',
  初上平: 'ĕ̤',
  初上上: 'ē̤',
  初上去: 'áe̤',
  初上入: 'áe̤h',
  初下平: 'è̤',
  初下去: 'âe̤',
  初下入: 'ĕ̤h',
  天上上: 'iēng',
  天上平: 'iĕng',
  天上去: 'iéng',
  天上入: 'iék',
  天下平: 'ièng',
  天下去: 'iêng',
  天下入: 'iĕk',
  奇上平: 'iă',
  奇上上: 'iā',
  奇上去: 'iá',
  奇上入: 'iáh',
  奇下平: 'ià',
  奇下去: 'iâ',
  奇下入: 'iăh',
  歪上平: 'uăi',
  歪上上: 'uāi',
  歪上去: 'uái',
  歪上入: 'uáih',
  歪下平: 'uài',
  歪下去: 'uâi',
  歪下入: 'uăih',
  溝上平: 'ĕu',
  溝上上: 'ēu',
  溝上去: 'áiu',
  溝上入: 'áiuh',
  溝下平: 'èu',
  溝下去: 'âiu',
  溝下入: 'ĕuh',
};

export const VOWELS = ['a', 'o', 'oo', 'e', 'eo', 'i', 'u', 'y', 'ng'] as const;
export type Vowels = (typeof VOWELS)[number];

export const yngpingVowelToneMap: Record<Vowels, Record<Tone, string>> = {
  a: {
    '': 'a',
    '0': 'ạ',
    '21': 'ǎ',
    '24': 'á',
    '242': 'â',
    '33': 'ā',
    '53': 'à',
    '5': 'a',
    '55': 'a',
  },
  o: {
    '': 'o',
    '0': 'ọ',
    '21': 'ǒ',
    '24': 'ó',
    '242': 'ô',
    '33': 'ō',
    '53': 'ò',
    '5': 'o',
    '55': 'o',
  },
  oo: {
    '': 'ö',
    '0': 'ọ̈',
    '21': 'ö̌',
    '24': 'ö́',
    '242': 'ö̂',
    '33': 'ȫ',
    '53': 'ö̀',
    '5': 'ö',
    '55': 'ö',
  },
  e: {
    '': 'e',
    '0': 'ẹ',
    '21': 'ě',
    '24': 'é',
    '242': 'ê',
    '33': 'ē',
    '53': 'è',
    '5': 'e',
    '55': 'e',
  },
  eo: {
    '': 'ë',
    '0': 'ẹ̈',
    '21': 'ë̌',
    '24': 'ë́',
    '242': 'ë̂',
    '33': 'ë̄',
    '53': 'ë̀',
    '5': 'ë',
    '55': 'ë',
  },
  i: {
    '': 'i',
    '0': 'ị',
    '21': 'ǐ',
    '24': 'í',
    '242': 'î',
    '33': 'ī',
    '53': 'ì',
    '5': 'i',
    '55': 'i',
  },
  u: {
    '': 'u',
    '0': 'ụ',
    '21': 'ǔ',
    '24': 'ú',
    '242': 'û',
    '33': 'ū',
    '53': 'ù',
    '5': 'u',
    '55': 'u',
  },
  y: {
    '': 'ü',
    '0': 'ụ̈',
    '21': 'ǚ',
    '24': 'ǘ',
    '242': 'ü̂',
    '33': 'ǖ',
    '53': 'ǜ',
    '5': 'ü',
    '55': 'ü',
  },
  ng: {
    '': 'ng',
    '0': 'ṇg',
    '21': 'ňg',
    '24': 'ńg',
    '242': 'n̂g',
    '33': 'n̄g',
    '53': 'ǹg',
    '5': 'ng',
    '55': 'ng',
  },
} as const;

export const yngpingTypingCursiveFinalMap: Record<Final, [string, Vowels]> = {
  a: ['a', 'a'],
  ai: ['ai', 'a'],
  au: ['au', 'a'],
  ang: ['ang', 'a'],
  aing: ['aing', 'a'],
  ah: ['ah', 'a'],
  ak: ['ak', 'a'],
  aik: ['aik', 'a'],
  e: ['e', 'e'],
  ei: ['ei', 'e'],
  eo: ['eo', 'eo'],
  eoy: ['eoü', 'eo'],
  eu: ['eu', 'e'],
  eing: ['eing', 'e'],
  eoyng: ['eoüng', 'eo'],
  eh: ['eh', 'e'],
  ek: ['ek', 'e'],
  eih: ['eih', 'e'],
  eik: ['eik', 'e'],
  eoh: ['eoh', 'eo'],
  eoyh: ['eoüh', 'eo'],
  eoyk: ['eoük', 'eo'],
  ooyk: ['ooük', 'oo'],
  i: ['i', 'i'],
  ia: ['ia', 'a'],
  iau: ['iau', 'a'],
  ie: ['ie', 'e'],
  ieu: ['ieu', 'e'],
  iu: ['iu', 'i'],
  ing: ['ing', 'i'],
  iang: ['iang', 'a'],
  ieng: ['ieng', 'e'],
  ih: ['ih', 'i'],
  ik: ['ik', 'i'],
  iah: ['iah', 'a'],
  iak: ['iak', 'a'],
  iauh: ['iauh', 'a'],
  ieh: ['ieh', 'e'],
  iek: ['iek', 'e'],
  ng: ['ng', 'ng'],
  o: ['o', 'o'],
  oo: ['oo', 'oo'],
  ou: ['ou', 'o'],
  ooy: ['ooü', 'oo'],
  ooyng: ['ooüng', 'oo'],
  ooung: ['ooung', 'oo'],
  oung: ['oung', 'o'],
  oh: ['oh', 'o'],
  ooh: ['ooh', 'oo'],
  oouk: ['oouk', 'oo'],
  ouh: ['ouh', 'o'],
  ouk: ['ouk', 'o'],
  u: ['u', 'u'],
  ua: ['ua', 'a'],
  uai: ['uai', 'a'],
  ui: ['ui', 'u'],
  uo: ['uo', 'u'],
  uoi: ['uoi', 'o'],
  ung: ['ung', 'u'],
  uang: ['uang', 'a'],
  uong: ['uong', 'o'],
  uh: ['uh', 'u'],
  uk: ['uk', 'u'],
  uah: ['uah', 'a'],
  uak: ['uak', 'a'],
  uoh: ['uoh', 'o'],
  uok: ['uok', 'o'],
  y: ['y', 'y'],
  yo: ['yo', 'o'],
  yng: ['yng', 'y'],
  yong: ['yong', 'o'],
  yh: ['yh', 'y'],
  yk: ['yk', 'y'],
  yoh: ['yoh', 'o'],
  yok: ['yok', 'o'],
} as const;
