name: Deploy Vue3 with Github Pages

on:
  push:
    branches: ["vue3-dev"]
  pull_request:
    branches: ["vue3-dev"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: GitHub Page Deploying
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        env:
          VITE_ENV_NAME: github-ci
          VITE_BASE_URL: /SeeDict
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_OSS_URL: ${{ secrets.VITE_OSS_URL }}
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
