name: Deploy Vue3 with Github Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: GitHub Page Deploying
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Install and Build 🔧
        env:
          VITE_ENV_NAME: github-ci
          VITE_BASE_URL: /seedict
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_API_V2_URL: ${{ vars.VITE_API_V2_URL }}
          VITE_OSS_URL: ${{ vars.VITE_OSS_URL }}
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
